#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>

namespace linecode::application {

// Language used to resolve the application-owned tool text catalog.
//
// The product has no shared AppLanguage type yet, so the tool layer carries the
// narrowest enum that covers the packaged locales instead of depending on a
// platform locale service it cannot reach off the composition thread.
enum class ToolTextLanguage : std::uint8_t {
  english,
  chinese,
};

// Every migrated legacy string resource the built-in file tools need.
//
// The catalog is owned by the application layer on purpose: huxerui::UseString
// is composition-bound and the platform resource service exposes no
// non-composition lookup, so background tool execution cannot resolve
// app::strings::* keys. The values are verbatim copies of
// resources/strings/default.properties and resources/strings/zh.properties,
// generated by tools/gen_tool_text_catalog.py, which fails when this
// enumeration and those files disagree.
//
// Declaration order is the properties file order and must stay in sync with the
// generated table in tool_text_catalog.cpp.
enum class ToolTextKey : std::uint8_t {
  tool_file_read_not_found,
  tool_file_read_dir_specify_file,
  tool_file_read_dir_content,
  tool_file_read_dir_truncated,
  tool_file_read_empty_dir,
  tool_file_read_start_out_of_range,
  tool_file_read_exceed_1mb,
  tool_file_read_exceed_50kb,
  tool_file_read_range_info,
  tool_file_read_failed,
  tool_file_write_created,
  tool_file_write_updated,
  tool_file_write_is_directory,
  tool_file_write_mkdir_failed,
  tool_file_write_failed,
  tool_file_edit_no_match,
  tool_file_edit_multiple_matches,
  tool_file_edit_success,
  tool_file_edit_failed,
  tool_file_edit_old_string_empty,
  tool_file_edit_is_directory,
  tool_file_edit_not_found,
  tool_file_delete_reason_empty,
  tool_file_delete_paths_empty,
  tool_file_delete_path_not_found,
  tool_file_delete_success,
  tool_file_delete_partial_fail,
  tool_file_delete_item_failed,
  tool_file_delete_none,
  tool_glob_root_not_found,
  tool_glob_no_match,
  tool_glob_found,
  tool_glob_truncated,
  tool_glob_failed,
  tool_list_dir_not_found,
  tool_list_dir_not_directory,
  tool_list_dir_empty,
  tool_list_dir_content,
  tool_list_dir_failed,
  tool_call_action_read,
  tool_call_action_list_dir,
  tool_call_action_match,
  tool_agent_invalid_type,
  tool_agent_explore_no_write,
  tool_agent_description_empty,
  tool_agent_prompt_empty,
  tool_agent_runner_not_available,
  tool_agent_parse_failed,
  tool_pipeline_agents_empty,
  tool_pipeline_agent_not_object,
  tool_pipeline_agent_id_empty,
  tool_pipeline_agent_id_duplicate,
  tool_pipeline_agent_self_depend,
  tool_pipeline_agent_invalid_type,
  tool_pipeline_explore_no_write,
  tool_pipeline_coding_needs_write,
  tool_pipeline_scope_duplicate,
  tool_pipeline_scope_overlap,
  tool_pipeline_agent_description_empty,
  tool_pipeline_agent_prompt_empty,
  tool_pipeline_runner_not_available,
  tool_agent_output_id_missing,
  tool_agent_output_store_missing,
  tool_agent_output_not_found,
  tool_agent_output_still_running,
  tool_agent_output_failed,
  tool_custom_agent_task_empty,
  tool_custom_agent_runner_not_available,
  tool_custom_agent_failed,
  tool_agent_output_empty,
};

// Number of ToolTextKey values, and the row count of the generated table.
inline constexpr std::size_t kToolTextKeyCount = 70;

// Packaged resource key of a catalog entry, such as "tool_file_read_failed".
[[nodiscard]] std::string_view ToolTextName(ToolTextKey key) noexcept;

// True when name is one of the packaged tool resource keys.
[[nodiscard]] bool IsToolTextKey(std::string_view name) noexcept;

// Raw localized template, still containing its {0}/{1} placeholders. Returns an
// empty view for an unknown key.
[[nodiscard]] std::string_view
ToolTextTemplate(std::string_view name,
                 ToolTextLanguage language = ToolTextLanguage::english) noexcept;
[[nodiscard]] std::string_view
ToolTextTemplate(ToolTextKey key,
                 ToolTextLanguage language = ToolTextLanguage::english) noexcept;

// Maps the app's locale probe (`app_locale_probe`, "en" / "zh") to the catalog
// language. HuxerUI exposes no "current locale" accessor -- a locale is only
// observable by resolving a resource during composition -- so the composition
// root resolves that probe and passes the answer down, which is why the
// catalog never guesses.
[[nodiscard]] constexpr ToolTextLanguage
ToolTextLanguageFor(std::string_view locale_probe) noexcept {
  return locale_probe == "zh" ? ToolTextLanguage::chinese
                              : ToolTextLanguage::english;
}

// Legacy positional formatting: {0}, {1}, ... are zero-based placeholders and
// {{ / }} are literal braces. A placeholder without a matching argument is kept
// verbatim, so a wrong argument count stays visible instead of silently empty.
[[nodiscard]] std::string
FormatToolText(std::string_view template_text,
               std::span<const std::string> arguments);

// Localized, formatted text for one catalog key. An unknown key echoes the key.
[[nodiscard]] std::string
ToolText(std::string_view name, std::span<const std::string> arguments,
         ToolTextLanguage language = ToolTextLanguage::english);
[[nodiscard]] std::string
ToolText(ToolTextKey key, std::span<const std::string> arguments,
         ToolTextLanguage language = ToolTextLanguage::english);

} // namespace linecode::application
