// Generated by tools/gen_tool_text_catalog.py - do not edit by hand.
//
// Verbatim copies of the tool_file_* / tool_glob_* / tool_list_dir_* /
// tool_call_action_* / tool_agent_* / tool_pipeline_* entries of
// resources/strings/default.properties (english)
// and resources/strings/zh.properties (chinese). Re-run
// `python3 tools/gen_tool_text_catalog.py` after changing those files.

#include "application/tool_text_catalog.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string>
#include <string_view>
#include <utility>

namespace linecode::application {
namespace {

// One localized template. `name` is the packaged resource key the text was
// migrated from, kept so the table can be diffed against the properties files.
struct ToolTextEntry final {
  ToolTextKey key;
  std::string_view name;
  std::string_view english;
  std::string_view chinese;
};

constexpr std::array<ToolTextEntry, kToolTextKeyCount> kToolTextEntries{{
    {
        .key = ToolTextKey::tool_file_read_not_found,
        .name = "tool_file_read_not_found",
        .english = "File not found: {0}",
        .chinese = "文件不存在: {0}",
    },
    {
        .key = ToolTextKey::tool_file_read_dir_specify_file,
        .name = "tool_file_read_dir_specify_file",
        .english = "\n\nTo read a file, specify the exact file path.",
        .chinese = "\n\n如需读取文件，请指定具体文件路径。",
    },
    {
        .key = ToolTextKey::tool_file_read_dir_content,
        .name = "tool_file_read_dir_content",
        .english = "Directory {0}:\n{1}",
        .chinese = "目录 {0}:\n{1}",
    },
    {
        .key = ToolTextKey::tool_file_read_dir_truncated,
        .name = "tool_file_read_dir_truncated",
        .english = "… (too many directory items, truncated)\n",
        .chinese = "… (目录项过多，已截断)\n",
    },
    {
        .key = ToolTextKey::tool_file_read_empty_dir,
        .name = "tool_file_read_empty_dir",
        .english = "(empty directory)",
        .chinese = "(空目录)",
    },
    {
        .key = ToolTextKey::tool_file_read_start_out_of_range,
        .name = "tool_file_read_start_out_of_range",
        .english = "start_kb={0} exceeds file size (file is {1}KB)",
        .chinese = "start_kb={0} 超出文件大小（文件共 {1}KB）",
    },
    {
        .key = ToolTextKey::tool_file_read_exceed_1mb,
        .name = "tool_file_read_exceed_1mb",
        .english = "File {0} is {1}KB, exceeding the 1MB read limit.\nUse start_kb/end_kb to specify a smaller range, e.g.: {{\"file_path\":\"{2}\",\"start_kb\":0,\"end_kb\":50}}",
        .chinese = "文件 {0} 大小为 {1}KB，超过 1MB 读取限制。\n请使用 start_kb/end_kb 指定更小的范围，例如：{{\"file_path\":\"{2}\",\"start_kb\":0,\"end_kb\":50}}",
    },
    {
        .key = ToolTextKey::tool_file_read_exceed_50kb,
        .name = "tool_file_read_exceed_50kb",
        .english = "File {0} is {1}KB, exceeding the 50KB single-read limit.\nUse start_kb and end_kb to specify the range, e.g.: {{\"file_path\":\"{2}\",\"start_kb\":0,\"end_kb\":50}}",
        .chinese = "文件 {0} 大小为 {1}KB，单次读取超过 50KB。\n请使用 start_kb 和 end_kb 指定读取范围，例如：{{\"file_path\":\"{2}\",\"start_kb\":0,\"end_kb\":50}}",
    },
    {
        .key = ToolTextKey::tool_file_read_range_info,
        .name = "tool_file_read_range_info",
        .english = "\n\n… (total {0} lines, showing KB {1}-{2} / total {3}KB)",
        .chinese = "\n\n… (共 {0} 行，显示 KB {1}-{2} / 共 {3}KB)",
    },
    {
        .key = ToolTextKey::tool_file_read_failed,
        .name = "tool_file_read_failed",
        .english = "Failed to read file: {0}",
        .chinese = "读取文件失败: {0}",
    },
    {
        .key = ToolTextKey::tool_file_write_created,
        .name = "tool_file_write_created",
        .english = "Successfully created file {0} ({1} lines)",
        .chinese = "成功创建文件 {0} ({1} 行)",
    },
    {
        .key = ToolTextKey::tool_file_write_updated,
        .name = "tool_file_write_updated",
        .english = "Successfully updated file {0} ({1} lines)",
        .chinese = "成功更新文件 {0} ({1} 行)",
    },
    {
        .key = ToolTextKey::tool_file_write_is_directory,
        .name = "tool_file_write_is_directory",
        .english = "Path is a directory, cannot write file: {0}\nTo create a file, specify the full file path.",
        .chinese = "路径是一个目录，无法写入文件: {0}\n如需创建文件，请指定完整文件路径。",
    },
    {
        .key = ToolTextKey::tool_file_write_mkdir_failed,
        .name = "tool_file_write_mkdir_failed",
        .english = "Failed to create parent directory: {0}",
        .chinese = "无法创建父目录: {0}",
    },
    {
        .key = ToolTextKey::tool_file_write_failed,
        .name = "tool_file_write_failed",
        .english = "Failed to write file: {0}",
        .chinese = "写入文件失败: {0}",
    },
    {
        .key = ToolTextKey::tool_file_edit_no_match,
        .name = "tool_file_edit_no_match",
        .english = "No matching text found",
        .chinese = "未找到匹配的文本",
    },
    {
        .key = ToolTextKey::tool_file_edit_multiple_matches,
        .name = "tool_file_edit_multiple_matches",
        .english = "old_string matched {0} places. Provide a more unique old_string, or set replace_all=true to replace every occurrence.",
        .chinese = "old_string 匹配到 {0} 处。请提供更唯一的 old_string，或设置 replace_all=true 以替换全部匹配。",
    },
    {
        .key = ToolTextKey::tool_file_edit_success,
        .name = "tool_file_edit_success",
        .english = "Successfully edited {0} ({1} match(es) replaced)",
        .chinese = "成功编辑文件 {0} ({1} 处匹配已替换)",
    },
    {
        .key = ToolTextKey::tool_file_edit_failed,
        .name = "tool_file_edit_failed",
        .english = "Failed to edit file: {0}",
        .chinese = "编辑文件失败: {0}",
    },
    {
        .key = ToolTextKey::tool_file_edit_old_string_empty,
        .name = "tool_file_edit_old_string_empty",
        .english = "old_string cannot be empty",
        .chinese = "old_string 不能为空",
    },
    {
        .key = ToolTextKey::tool_file_edit_is_directory,
        .name = "tool_file_edit_is_directory",
        .english = "Path is a directory, cannot edit: {0}\nTo edit a file, specify the exact file path.",
        .chinese = "路径是一个目录，无法编辑文件: {0}\n如需编辑文件，请指定具体文件路径。",
    },
    {
        .key = ToolTextKey::tool_file_edit_not_found,
        .name = "tool_file_edit_not_found",
        .english = "File not found: {0}",
        .chinese = "文件不存在: {0}",
    },
    {
        .key = ToolTextKey::tool_file_delete_reason_empty,
        .name = "tool_file_delete_reason_empty",
        .english = "Deletion reason cannot be empty",
        .chinese = "删除原因 reason 不能为空",
    },
    {
        .key = ToolTextKey::tool_file_delete_paths_empty,
        .name = "tool_file_delete_paths_empty",
        .english = "paths cannot be empty",
        .chinese = "paths 不能为空",
    },
    {
        .key = ToolTextKey::tool_file_delete_path_not_found,
        .name = "tool_file_delete_path_not_found",
        .english = "Path not found: {0}",
        .chinese = "路径不存在: {0}",
    },
    {
        .key = ToolTextKey::tool_file_delete_success,
        .name = "tool_file_delete_success",
        .english = "Successfully deleted {0} item(s):\n",
        .chinese = "成功删除 {0} 项:\n",
    },
    {
        .key = ToolTextKey::tool_file_delete_partial_fail,
        .name = "tool_file_delete_partial_fail",
        .english = "Failed {0} item(s):\n",
        .chinese = "失败 {0} 项:\n",
    },
    {
        .key = ToolTextKey::tool_file_delete_item_failed,
        .name = "tool_file_delete_item_failed",
        .english = "Failed to delete {0}: {1}",
        .chinese = "删除 {0} 失败: {1}",
    },
    {
        .key = ToolTextKey::tool_file_delete_none,
        .name = "tool_file_delete_none",
        .english = "No files were deleted",
        .chinese = "没有删除任何文件",
    },
    {
        .key = ToolTextKey::tool_glob_root_not_found,
        .name = "tool_glob_root_not_found",
        .english = "Search root directory does not exist or is not a directory: {0}",
        .chinese = "搜索根目录不存在或不是目录: {0}",
    },
    {
        .key = ToolTextKey::tool_glob_no_match,
        .name = "tool_glob_no_match",
        .english = "No files matching \"{0}\" found in {1}.",
        .chinese = "在 {1} 目录下未找到匹配 \"{0}\" 的文件。",
    },
    {
        .key = ToolTextKey::tool_glob_found,
        .name = "tool_glob_found",
        .english = "Found {0} matching file(s) in {1}:\n",
        .chinese = "在 {1} 目录下找到 {0} 个匹配文件:\n",
    },
    {
        .key = ToolTextKey::tool_glob_truncated,
        .name = "tool_glob_truncated",
        .english = "… (too many results, truncated)\n",
        .chinese = "… (结果过多，已截断)\n",
    },
    {
        .key = ToolTextKey::tool_glob_failed,
        .name = "tool_glob_failed",
        .english = "Search failed: {0}",
        .chinese = "搜索失败: {0}",
    },
    {
        .key = ToolTextKey::tool_list_dir_not_found,
        .name = "tool_list_dir_not_found",
        .english = "Directory not found: {0}",
        .chinese = "目录不存在: {0}",
    },
    {
        .key = ToolTextKey::tool_list_dir_not_directory,
        .name = "tool_list_dir_not_directory",
        .english = "Path is not a directory: {0}",
        .chinese = "路径不是目录: {0}",
    },
    {
        .key = ToolTextKey::tool_list_dir_empty,
        .name = "tool_list_dir_empty",
        .english = "Directory {0}:\n(empty directory)",
        .chinese = "目录 {0}:\n(空目录)",
    },
    {
        .key = ToolTextKey::tool_list_dir_content,
        .name = "tool_list_dir_content",
        .english = "Directory {0}:\n",
        .chinese = "目录 {0}:\n",
    },
    {
        .key = ToolTextKey::tool_list_dir_failed,
        .name = "tool_list_dir_failed",
        .english = "Failed to list directory: {0}",
        .chinese = "列目录失败: {0}",
    },
    {
        .key = ToolTextKey::tool_call_action_read,
        .name = "tool_call_action_read",
        .english = "Read",
        .chinese = "读取",
    },
    {
        .key = ToolTextKey::tool_call_action_list_dir,
        .name = "tool_call_action_list_dir",
        .english = "List directory",
        .chinese = "列目录",
    },
    {
        .key = ToolTextKey::tool_call_action_match,
        .name = "tool_call_action_match",
        .english = "Search files",
        .chinese = "匹配",
    },
    {
        .key = ToolTextKey::tool_agent_invalid_type,
        .name = "tool_agent_invalid_type",
        .english = "Agent type must be explore or sub-coding.",
        .chinese = "Agent 类型只能是 explore 或 sub-coding。",
    },
    {
        .key = ToolTextKey::tool_agent_explore_no_write,
        .name = "tool_agent_explore_no_write",
        .english = "explore Agent cannot declare write_scope and cannot write files.",
        .chinese = "explore Agent 不能声明 write_scope，也不能写入文件。",
    },
    {
        .key = ToolTextKey::tool_agent_description_empty,
        .name = "tool_agent_description_empty",
        .english = "Agent description cannot be empty.",
        .chinese = "Agent description 不能为空。",
    },
    {
        .key = ToolTextKey::tool_agent_prompt_empty,
        .name = "tool_agent_prompt_empty",
        .english = "Agent prompt cannot be empty.",
        .chinese = "Agent prompt 不能为空。",
    },
    {
        .key = ToolTextKey::tool_agent_runner_not_available,
        .name = "tool_agent_runner_not_available",
        .english = "Agent runner not available, cannot run sub-Agent.",
        .chinese = "Agent 执行器未接入，无法运行子 Agent。",
    },
    {
        .key = ToolTextKey::tool_agent_parse_failed,
        .name = "tool_agent_parse_failed",
        .english = "Agent parameter parsing failed: {0}",
        .chinese = "Agent 参数解析失败: {0}",
    },
    {
        .key = ToolTextKey::tool_pipeline_agents_empty,
        .name = "tool_pipeline_agents_empty",
        .english = "agent_pipeline.agents cannot be empty.",
        .chinese = "agent_pipeline.agents 不能为空。",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_not_object,
        .name = "tool_pipeline_agent_not_object",
        .english = "agents[{0}] must be an object.",
        .chinese = "agents[{0}] 必须是对象。",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_id_empty,
        .name = "tool_pipeline_agent_id_empty",
        .english = "agents[{0}].id cannot be empty.",
        .chinese = "agents[{0}].id 不能为空。",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_id_duplicate,
        .name = "tool_pipeline_agent_id_duplicate",
        .english = "Agent id duplicate: {0}",
        .chinese = "Agent id 重复: {0}",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_self_depend,
        .name = "tool_pipeline_agent_self_depend",
        .english = "Agent cannot depend on itself: {0}",
        .chinese = "Agent 不能依赖自身: {0}",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_invalid_type,
        .name = "tool_pipeline_agent_invalid_type",
        .english = "agents[{0}].type must be explore or sub-coding.",
        .chinese = "agents[{0}].type 只能是 explore 或 sub-coding。",
    },
    {
        .key = ToolTextKey::tool_pipeline_explore_no_write,
        .name = "tool_pipeline_explore_no_write",
        .english = "explore Agent cannot declare write_scope and cannot write files: {0}",
        .chinese = "explore Agent 不能声明 write_scope，也不能写入文件: {0}",
    },
    {
        .key = ToolTextKey::tool_pipeline_coding_needs_write,
        .name = "tool_pipeline_coding_needs_write",
        .english = "sub-coding Agent must declare write_scope to avoid multiple Agents writing the same file: {0}",
        .chinese = "sub-coding Agent 必须声明 write_scope，避免多个 Agent 操纵同一文件: {0}",
    },
    {
        .key = ToolTextKey::tool_pipeline_scope_duplicate,
        .name = "tool_pipeline_scope_duplicate",
        .english = "Agent {0} has duplicate write_scope: {1}",
        .chinese = "Agent {0} 的 write_scope 重复: {1}",
    },
    {
        .key = ToolTextKey::tool_pipeline_scope_overlap,
        .name = "tool_pipeline_scope_overlap",
        .english = "Multiple Agents cannot write the same file or overlapping directories: {0}'s {1} conflicts with {2}'s {3}. Please merge into one Agent or split into different files/directories.",
        .chinese = "多个 Agent 不能写同一文件或重叠目录: {0} 的 {1} 与 {2} 的 {3} 冲突。请合并为一个 Agent，或拆成不同文件/目录后再分配。",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_description_empty,
        .name = "tool_pipeline_agent_description_empty",
        .english = "agents[{0}].description cannot be empty.",
        .chinese = "agents[{0}].description 不能为空。",
    },
    {
        .key = ToolTextKey::tool_pipeline_agent_prompt_empty,
        .name = "tool_pipeline_agent_prompt_empty",
        .english = "agents[{0}].prompt cannot be empty.",
        .chinese = "agents[{0}].prompt 不能为空。",
    },
    {
        .key = ToolTextKey::tool_pipeline_runner_not_available,
        .name = "tool_pipeline_runner_not_available",
        .english = "Agent pipeline runner not available, cannot run.",
        .chinese = "Agent 流水线执行器未接入，无法运行。",
    },
    {
        .key = ToolTextKey::tool_agent_output_id_missing,
        .name = "tool_agent_output_id_missing",
        .english = "agent_id is required.",
        .chinese = "必须提供 agent_id。",
    },
    {
        .key = ToolTextKey::tool_agent_output_store_missing,
        .name = "tool_agent_output_store_missing",
        .english = "Agent result store is not available.",
        .chinese = "Agent 结果存储不可用。",
    },
    {
        .key = ToolTextKey::tool_agent_output_not_found,
        .name = "tool_agent_output_not_found",
        .english = "Unknown agent_id: {0}",
        .chinese = "未知 agent_id: {0}",
    },
    {
        .key = ToolTextKey::tool_agent_output_still_running,
        .name = "tool_agent_output_still_running",
        .english = "Agent is still running. Poll again later or wait for completion.",
        .chinese = "Agent 仍在运行。请稍后再次查询，或等待其完成。",
    },
    {
        .key = ToolTextKey::tool_agent_output_failed,
        .name = "tool_agent_output_failed",
        .english = "Agent finished with error.",
        .chinese = "Agent 以错误结束。",
    },
    {
        .key = ToolTextKey::tool_agent_output_empty,
        .name = "tool_agent_output_empty",
        .english = "Agent finished with empty output.",
        .chinese = "Agent 结束但输出为空。",
    },
}};

static_assert(kToolTextEntries.size() == kToolTextKeyCount,
              "kToolTextEntries must cover every ToolTextKey");

// The table mirrors the ToolTextKey enumeration, so the ordinal lookup below is
// a direct index and a reordering mistake fails the build instead of silently
// crossing two strings.
consteval bool ToolTextTableIsOrdered() {
  for (std::size_t index = 0; index < kToolTextEntries.size(); ++index) {
    if (std::to_underlying(kToolTextEntries[index].key) != index)
      return false;
  }
  return true;
}

static_assert(ToolTextTableIsOrdered(),
              "ToolTextKey declaration order must match kToolTextEntries");

const ToolTextEntry *FindEntry(ToolTextKey key) noexcept {
  return &kToolTextEntries[static_cast<std::size_t>(std::to_underlying(key))];
}

const ToolTextEntry *FindEntry(std::string_view name) noexcept {
  const auto found =
      std::ranges::find(kToolTextEntries, name, &ToolTextEntry::name);
  return found == kToolTextEntries.end() ? nullptr : &*found;
}

std::string_view Select(const ToolTextEntry &entry,
                        ToolTextLanguage language) noexcept {
  return language == ToolTextLanguage::chinese ? entry.chinese : entry.english;
}

// The legacy positional template syntax: `{0}`-style placeholders are
// zero-based, `{{` and `}}` are literal braces, and any other brace is
// copied through unchanged. A placeholder without a matching argument is kept
// verbatim so a mismatched call is visible instead of silently empty.
std::string FormatTemplate(std::string_view template_text,
                           std::span<const std::string> arguments) {
  constexpr std::size_t kMaximumPlaceholderDigits = 4;
  std::string formatted;
  formatted.reserve(template_text.size());
  for (std::size_t index = 0; index < template_text.size(); ++index) {
    const char character = template_text[index];
    if (character == '{') {
      if (index + 1U < template_text.size() && template_text[index + 1U] == '{') {
        formatted += '{';
        ++index;
        continue;
      }
      std::size_t cursor = index + 1U;
      std::size_t placeholder = 0;
      while (cursor < template_text.size() &&
             cursor - index <= kMaximumPlaceholderDigits &&
             std::isdigit(static_cast<unsigned char>(template_text[cursor])) != 0) {
        placeholder = placeholder * 10U +
                      static_cast<std::size_t>(template_text[cursor] - '0');
        ++cursor;
      }
      if (cursor > index + 1U && cursor < template_text.size() &&
          template_text[cursor] == '}') {
        if (placeholder < arguments.size())
          formatted += arguments[placeholder];
        else
          formatted.append(template_text.substr(index, cursor - index + 1U));
        index = cursor;
        continue;
      }
      formatted += character;
      continue;
    }
    if (character == '}' && index + 1U < template_text.size() &&
        template_text[index + 1U] == '}') {
      formatted += '}';
      ++index;
      continue;
    }
    formatted += character;
  }
  return formatted;
}

} // namespace

std::string_view ToolTextName(ToolTextKey key) noexcept {
  return FindEntry(key)->name;
}

bool IsToolTextKey(std::string_view name) noexcept {
  return FindEntry(name) != nullptr;
}

std::string_view ToolTextTemplate(std::string_view name,
                                  ToolTextLanguage language) noexcept {
  const ToolTextEntry *entry = FindEntry(name);
  return entry == nullptr ? std::string_view{} : Select(*entry, language);
}

std::string_view ToolTextTemplate(ToolTextKey key,
                                  ToolTextLanguage language) noexcept {
  return Select(*FindEntry(key), language);
}

std::string FormatToolText(std::string_view template_text,
                           std::span<const std::string> arguments) {
  return FormatTemplate(template_text, arguments);
}

std::string ToolText(std::string_view name,
                     std::span<const std::string> arguments,
                     ToolTextLanguage language) {
  const ToolTextEntry *entry = FindEntry(name);
  // An unknown key echoes the key so a typo is visible at the call site.
  return entry == nullptr ? std::string{name}
                          : FormatTemplate(Select(*entry, language), arguments);
}

std::string ToolText(ToolTextKey key, std::span<const std::string> arguments,
                     ToolTextLanguage language) {
  return FormatTemplate(Select(*FindEntry(key), language), arguments);
}

} // namespace linecode::application
